### ISSUE TITLE
Integration with MNE

### ISSUE THREAD

**Issue by christian-oreilly** [christian-oreilly/infant_template_paper#2]
In order to integrate the templates with MNE, we would want to compute and add to the templates the following artifacts:

- SUBJECT/bem/SUBJECT-5120-5120-5120-bem-sol.fif
- SUBJECT/bem/SUBJECT-5120-5120-5120-bem.fif
- SUBJECT/bem/SUBJECT-fiducials.fif
- SUBJECT/bem/SUBJECT-head.fif
- SUBJECT/bem/SUBJECT-oct-6-src.fif (maybe?)
- SUBJECT/bem/SUBJECT-vol-5-src.fif (maybe?)

**Comment by christian-oreilly** [comment]
@larsoner If you are ok with it, I'll just integrate a copy of your gist https://gist.github.com/larsoner/72703fb3e37ae7082479c0591a4bee72 to the end of the pipeline since it already produces all these files and I trust more your parametrization than mine when comes to using MNE. 

It should all be ready to go shortly. I am just finalizing updating the montage and fiducial files for issue #1 and then the new templates including these additional will be uploaded.

**Comment by larsoner** [comment]
Yes feel free. FWIW you shouldn't need to hack the coordinate frame attribute anymore (it should be correct when you read the data) and now saving in non-head coord frame is supported: https://github.com/mne-tools/mne-python/pull/8532. If it's not clear how to do this, just open a PR to add some variant of my changes and I can push simplifying commits.

**Comment by christian-oreilly** [comment]
@larsoner After verification, using 
```
    montage = mne.channels.make_dig_montage(...,  coord_frame="mri")    
    montage.save(montage_fname)
```

has the inverse effect than what I am looking for. Here is with `coord_frame="mri"`

![Screenshot from 2020-11-20 16-38-38](https://user-images.githubusercontent.com/5932954/99852499-1e8e8700-2b4f-11eb-9e2b-892658290fee.png)

And this is with `coord_frame="head"`

![Screenshot from 2020-11-20 16-38-33](https://user-images.githubusercontent.com/5932954/99852487-18000f80-2b4f-11eb-9e53-eb42c339ab00.png)

If I understand this right, when using `coord_frame="mri"`, MNE transforms the montage according to the fiducials. That is not what I want. I want these coordinates the remain as they are. They are already fit to the surfaces and they are already in a normalized space (Talairach/MNI system with AC at [0,0,0]). They should not be modified.

**Comment by larsoner** [comment]
> has the inverse effect than what I am looking for. Here is with coord_frame="mri"

Can you post the code for how you are making this plot? My guess is that you are doing `trans=None`, which is incorrect. There should be a non-identity transform from MRI to the head coordinate frame.

**Comment by larsoner** [comment]
For inspiration, look at this tutorial which deals directly with montages in MRI coordinate frame, and gets a proper non-identity `trans`:

https://mne.tools/dev/auto_tutorials/misc/plot_seeg.html#sphx-glr-auto-tutorials-misc-plot-seeg-py

**Comment by christian-oreilly** [comment]
Quite accurately guessed, I used trans=None because the electrodes were meant to be already at the right place with respect to the surfaces so not needing further transformation to co-register them. In any case, it works fine with `trans = mne.channels.compute_native_head_t(montage)`.

**Comment by christian-oreilly** [comment]
@larsoner I just made a release for the templates ( https://github.com/christian-oreilly/infant_template_paper/releases/tag/v0.1-alpha ). I think it is the best way to share the templates through GitHub due to the size of the files. I initially added the templates directly to the git repo, but it started to fail when adding the MNE-Python bem files which are over 100 Mb. I checked for using lfs, but the 13 templates makes for a bit more than 4.0 Gb and the free GitHub account has a limit at 1.0 Gb. So I think releases will be the best solution. This release should have all you asked for so far: FreeSurfer-base decimation, FLIT transform matrices, FLIRT-transformed atlases from the MND, mri-space (instead of head-space) montage, and the MNE-Python files that are produced by the gist you shared. Let me know if you observe any other issue or if you are missing anything.

**Comment by christian-oreilly** [comment]
Just re-opened the issue because I should not have closed it with this commit since the "integration with MNE" is not done. We most certainly have more to discuss to add some mechanism that make it easier for MNE-Python to uses these templates more or less transparently (a bit like for using fsaverage). Any idea on that @larsoner ?

**Comment by larsoner** [comment]
Yes I think we can make a `fetch_infant_template(age='all' | '3mo' | ['3mo', '6mo'], ...)`. For `fsaverage` we basically just made a list of files that is included in the collection, plus a single `zip` that had all the files. I can start working on this, hopefully this week.

**Comment by larsoner** [comment]
> I think it is the best way to share the templates through GitHub due to the size of the files.

So the release has more than the only the `git` repo contents attached / included it somehow? Like you manually uploaded a `tar.gz` or something? I have never done anything other than just have the files from the repo packaged up so I am curious...

**Comment by christian-oreilly** [comment]
> Yes I think we can make a fetch_infant_template(age='all' | '3mo' | ['3mo', '6mo'], ...). For fsaverage we basically just made a list of files that is included in the collection, plus a single zip that had all the files. I can start working on this, hopefully this week.

Sounds great. Let me know if you need anything from me on that topic.

> So the release has more than the only the git repo contents attached / included it somehow? Like you manually uploaded a tar.gz or something? I have never done anything other than just have the files from the repo packaged up so I am curious...

Yes, exactly. I did not use any automated GitHub process to generate the release. The zips (one per template) are generated by the modelling pipeline. I created the release manually though GibHub interface ( https://github.com/christian-oreilly/infant_template_paper/releases/new ). I just uploaded the 13 template zips manually and GitHub automatically added the source code archive to it.

**Comment by larsoner** [comment]
@christian-oreilly sorry for the delays on this, I think I'll aim to do this early January since we are pushing out MNE 0.22 now

**Comment by christian-oreilly** [comment]
Sure, no problem @larsoner I don't think this is urgent at the moment.

**Comment by larsoner** [comment]
We should close in favor of https://github.com/mne-tools/mne-python/pull/8738 and I'll open more targeted issues if problems arise

**Comment by christian-oreilly** [comment]
Agreed.
