### ISSUE TITLE
BUG: Files not available on git clone

### ISSUE THREAD

**Issue by larsoner** [christian-oreilly/infant_template_paper#5]
I'm working toward #2 and can no longer `git clone`:
```
larsoner@bunk:~/python$ git clone git@github.com:/christian-oreilly/infant_template_paper.git
Cloning into 'infant_template_paper'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 1261 (delta 5), reused 46 (delta 4), pack-reused 1200
Receiving objects: 100% (1261/1261), 649.52 MiB | 43.55 MiB/s, done.
Resolving deltas: 100% (113/113), done.
Downloading Templates/ANTS1-0Months3T.zip (336 MB)
Error downloading object: Templates/ANTS1-0Months3T.zip (0b47676): Smudge error: Error downloading Templates/ANTS1-0Months3T.zip (0b4767620a442f02f196c9618709cc4eb19abba1481d8f3e65837a18ed84af14): batch response: Git LFS is disabled for this repository.

Errors logged to /home/larsoner/python/infant_template_paper/.git/lfs/logs/20210112T115423.922689879.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Templates/ANTS1-0Months3T.zip: smudge filter lfs failed
```
1. Any ideas @christian-oreilly ? Based on some light searching this suggests that GitHub might have killed your uploads because they are over some quota (?).
2. Are the `.zip` files you made just the contents immediately preceding the removal of the files from the repo? If so then I can at least still make progress on #2 while the LFS stuff is sorted out.
3. Any idea if there will be direct-download URLs available? It would be nice if users can directly download the `.zip` files from somewhere, that way end-users don't need `git` plus `git-lfs` on their systems...

**Comment by christian-oreilly** [comment]
I tried git-lfs and it caused issue because of quota and stuff like that. So I changed the approaches and used releases which does contain zip files that can be dowloaded as zip files. See for example https://github.com/christian-oreilly/infant_template_paper/releases/latest

I though that all big files that were causing issues (i.e., all zip files in the Template directory) were removed at that time... but looks like I did not finished this cleaning up. I'll remove them from the git code repo... zip should be downloaded through the latest "release".

**Comment by christian-oreilly** [comment]
OK. Done. The Templates directory has been remove from GIT altogether. This directory will be created we we run the pipeline, but it should remain a local directory only. When creating a release, I will uploaded the zip as assets in the release but they won't be added to the gitted (if that is word) code. Let me know if that solve your issue.

**Comment by larsoner** [comment]
Yep, locally doing:
```
git clone git@github.com:/christian-oreilly/infant_template_paper.git --depth=1
```
(depth=1 just to avoid downloading all the old commits with lots of data) works just fine now!
